### ISSUE TITLE
Question: how do you find the function hash "b61d27f6"

### ISSUE THREAD

**Issue by lyricalpolymath** [bokkypoobah/TheDAOData#1]
@bokkypoobah this is more a question than an issue
I've noticed this in your https://github.com/bokkypoobah/TheDAOData/blob/master/getTheDAOCreatedTokenEventsWithNonZeroExtraBalance_v3 

`else if (stack[0].substring(56) == "b61d27f6")`

**how did you come up with this and what does it mean?**

I did some digging, but I didn't come up with much
by looking at [this gist](https://gist.github.com/CJentzsch/f28933cd47a2696a57f1) it seems to be the hash of the execute function

> b61d27f6:  execute(address,uint256,bytes)

but I couldn't reproduce the hash from that signature 
either using this https://emn178.github.io/online-tools/keccak_256.html

nor did I find it in the link you suggest to retrieve the fuction hashes
https://www.4byte.directory/signatures/?bytes4_signature=0xbaac5300
https://www.4byte.directory/signatures/?bytes4_signature=0xb61d27f6
which doesn't seem to work any more

by tracing the transactions and looking at the CALL functions stacks I've noticed that most (if not probably all) smart contract addresses have that function has as the first paramenter. Why is that?

for instance, here are the 2 CALL functions for transaction '0x694d35e8cacd209636e042e09681491ee82f15424e55db1e23fe7146af2337ad'

```
[{
    depth: 1,
    error: "",
    gas: 25007,
    gasCost: 96722,
    memory: ["0000000000000000000000003a1dd9ceec16c17d74a31f64040a77a6a6dec33d", "0000000000000000000000000000000000000000000000000000000000000102", "0000000000000000000000000000000000000000000000000000000000000060", "0000000000000000000000003a1dd9ceec16c17d74a31f64040a77a6a6dec33d", "0000000000000000000000000000000000000000000000030927f74c9de00000", "000000000000000000000000bb9bc244d798123fde783fcc1c72d3bb8c189413", "0000000000000000000000000000000000000000000000000000000000000080", "0000000000000000000000000000000000000000000000000000000000000000"],
    op: "CALL",
    pc: 3215,
    stack: ["00000000000000000000000000000000000000000000000000000000b61d27f6", "00000000000000000000000000000000000000000000000000000000000002f1", "000000000000000000000000bb9bc244d798123fde783fcc1c72d3bb8c189413", "0000000000000000000000000000000000000000000000030927f74c9de00000", "0000000000000000000000000000000000000000000000000000000000000084", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "000000000000000000000000bb9bc244d798123fde783fcc1c72d3bb8c189413", "0000000000000000000000000000000000000000000000030927f74c9de00000", "0000000000000000000000000000000000000000000000000000000000000060", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000060", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000060", "0000000000000000000000000000000000000000000000030927f74c9de00000", "000000000000000000000000bb9bc244d798123fde783fcc1c72d3bb8c189413", "0000000000000000000000000000000000000000000000000000000000015682"],
    storage: {
      0000000000000000000000000000000000000000000000000000000000000106: "0000000000000000000000000000000000000000000000030927f74c9de00000",
      0000000000000000000000000000000000000000000000000000000000000107: "0000000000000000000000000000000000000000000000000000000000004235"
    }
}, {
    depth: 2,
    error: "",
    gas: 25007,
    gasCost: 64055,
    memory: ["0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000060"],
    op: "CALL",
    pc: 2761,
    stack: ["0000000000000000000000000000000000000000000000000000000000000966", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000980", "000000000000000000000000050f81ae80a07542a70bb52f15895e347164f867", "0000000000000000000000000000000000000000000000000000000000000000", "000000000000000000000000000000000000000000000002061aa4ddbe955555", "000000000000000000000000807640a13483f8ac783c557fcdf27be11ea4ac7a", "000000000000000000000000000000000000000000000001030d526edf4aaaab", "0000000000000000000000000000000000000000000000000000000000000060", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000060", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000060", "000000000000000000000000000000000000000000000001030d526edf4aaaab", "000000000000000000000000807640a13483f8ac783c557fcdf27be11ea4ac7a", "000000000000000000000000000000000000000000000000000000000000d6e7"],
    storage: {}
}]
```

**Comment by bokkypoobah** [comment]
It is the first part of the sha3 hash of `execute(address,uint256,bytes)`. In `geth` the following command produces the hash:

```
> web3.sha3('execute(address,uint256,bytes)')
"0xb61d27f68746b0955d4867ce6e77d35c62208909547ca5c62d2a533c00d5b837"
> web3.sha3('execute(address,uint256,bytes)').substring(0,10)
"0xb61d27f6"
```

This is the amount that is transferred by the wallet contract `execute(...)` function.

Thanks for checking.

**Comment by lyricalpolymath** [comment]
**EDITED (for my mistake)**
hey thanks for your reply :) - I was still writing this follow up doubt :)

I also think there might be a mistake in line 74 

```
else if (stack[0].substring(56) == "b61d27f6") {
        amount = web3.toBigNumber("0x" + stack[stack.length-3]);
```
- **the amount refers to the amount sent to theDAO not to the extraBalance**
  56000000000000000000 or 56 ETH
  that you can [check in etherscan](http://etherscan.io/tx/0x694d35e8cacd209636e042e09681491ee82f15424e55db1e23fe7146af2337ad)

try it like this 

```
//the stack is saved from tracing transaction '0x694d35e8cacd209636e042e09681491ee82f15424e55db1e23fe7146af2337ad'
//and finding the first CALL
var stack = ["00000000000000000000000000000000000000000000000000000000b61d27f6", "00000000000000000000000000000000000000000000000000000000000002f1", "000000000000000000000000bb9bc244d798123fde783fcc1c72d3bb8c189413", "0000000000000000000000000000000000000000000000030927f74c9de00000", "0000000000000000000000000000000000000000000000000000000000000084", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "000000000000000000000000bb9bc244d798123fde783fcc1c72d3bb8c189413", "0000000000000000000000000000000000000000000000030927f74c9de00000", "0000000000000000000000000000000000000000000000000000000000000060", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000060", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000060", "0000000000000000000000000000000000000000000000030927f74c9de00000", "000000000000000000000000bb9bc244d798123fde783fcc1c72d3bb8c189413", "0000000000000000000000000000000000000000000000000000000000015682"]

var amount = web3.toBigNumber("0x" + stack[stack.length-3]);
console.log("amount: " + amount) // 56000000000000000000

```

**Comment by bokkypoobah** [comment]
Yup. The extraBalance amount is picked up by the statement:

```
extraBalanceAmount = web3.toBigNumber("0x" + stack[stack.length-3]);
```

And the statement you highlighted picks up the amount that the wallet sends to The DAO.

**Comment by lyricalpolymath** [comment]
yes I've seen that, but in the case the stack is like the one I wrote you earlier on
(when stack[0].substring(56) == "b61d27f6")
both amount and extraBalanceAmount are the same
they extract the same values from the stack

`extraBalanceAmount = web3.toBigNumber("0x" + stack[stack.length-3]);`

and

`amount = web3.toBigNumber("0x" + stack[stack.length-3]);`

therefore when you do 
`var theDAOAmount = amount - extraBalanceAmount;` will be zero
- more importantly the extraBalanceAmount is not at that index if the function is "b61d27f6"
  there is no extraBalance at that function... you should probably avoid reading alltogether from that functions and only read the extraBalance if you can read the other 2 function hashes (""00000966" and "baac5300")  
- also, I've noticed that in the case the user sends an inputData with the call, the funcHash won't be at the index 0 of the stack, but will be shifted down 1 position to 
  stack[1].substring(56)
  look for example at this transaction http://etherscan.io/tx/0xeea3be70ab2204693fb0bc30a37ab09aa47f790bd61f058efd7c2be4fa64a66b
  where the input data is "dao"  
  the stack will be moved one index down

**Comment by bokkypoobah** [comment]
What happens is that I'm expecting the second "CALL" stack data to overwrite the amount figure.

```
var stack = ["0000000000000000000000000000000000000000000000000000000000000966", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000980", "000000000000000000000000050f81ae80a07542a70bb52f15895e347164f867", "0000000000000000000000000000000000000000000000000000000000000000", "000000000000000000000000000000000000000000000002061aa4ddbe955555", "000000000000000000000000807640a13483f8ac783c557fcdf27be11ea4ac7a", "000000000000000000000000000000000000000000000001030d526edf4aaaab", "0000000000000000000000000000000000000000000000000000000000000060", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000060", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000060", "000000000000000000000000000000000000000000000001030d526edf4aaaab", "000000000000000000000000807640a13483f8ac783c557fcdf27be11ea4ac7a", "000000000000000000000000000000000000000000000000000000000000d6e7"];

var amount = web3.toBigNumber("0x" + stack[stack.length-3]);
console.log("amount: " + amount) 
// amount: 18666666666666666667
```

**Comment by bokkypoobah** [comment]
And regarding your extra data in your Tx http://etherscan.io/tx/0xeea3be70ab2204693fb0bc30a37ab09aa47f790bd61f058efd7c2be4fa64a66b, here is the corresponding data from the spreadsheet

```
From    TokenOwner  CreatedBy   BlockNumber TxHash  Timestamp   GMTDateTime Amount  TheDAOAmount    extraBalanceAmount  TheDAOTokens    GasUsed GasPrice    Cost    Nonce   Error
0x416bdadc20ae5238ea7b1373fb783e893d51048e  0x416bdadc20ae5238ea7b1373fb783e893d51048e  Owner   1537724 0xeea3be70ab2204693fb0bc30a37ab09aa47f790bd61f058efd7c2be4fa64a66b  1463544493  Wed, 18 May 2016 04:08:13 GMT   35.985  31.2913043478   4.6936956522    3129.1304347826 82281   50000000000 0.00411405  0   
```

Or

```
Amount 35.985
TheDAOAmount 31.2913043478
extraBalanceAmount 4.6936956522
TheDAOTokens 3129.1304347826
```

**Comment by lyricalpolymath** [comment]
oh yes.. seen it now :)
sorry. 
but going back to the first question. how did you know to look for "b61d27f6" in the first place? :)

**Comment by bokkypoobah** [comment]
Reverse engineering. I used some sample transactions, extracted the "CALL" traces, searched for the addresses and amounts required then worked out which signature to look for. The 4bytes site was down so I did not document the function declaration for the wallet execute() but I saw the same signature across several wallet type transactions. 

Thanks again for checking.

Something else to verify if you have the time - https://github.com/bokkypoobah/TheDAOETCTokenBalance .

**Comment by lyricalpolymath** [comment]
ok, like I was doing too :) 
I thought you might have a special trick :)

I've noticed also other types of func hashes 
I've seen many "797af627"

for example in this 
address: 0x7da7ec4d7342b0a088f3c0e9dea9a6bf92fb5088 txs: 3
transaction hash: 0xa1bf21e115847970a88ff433c70ecec22924c34961605e5777fa989c870e6ed4 - found 2 CALL functions:
CALL1 > s0: 797af627    s1: 00000356 

Has input Data 0x797af6271a8078d10979531767d0cf073228575b773df9e8c6975408a8c9c8246299455d

and found it also in other contracts and transactions like this
http://etherscan.io/tx/0xb53834fc8a6c3df178a84dd4026afeef3139ca4f0092c81546aaa2537fb09615

but I'm not sure what it means

thanks for your very instructive code :)
