### ISSUE TITLE
small rounding error in ETH calculation of the extraBalance

### ISSUE THREAD

**Issue by lyricalpolymath** [bokkypoobah/TheDAOData#2]
Hi Bokkypoobah
I've confronted my final script https://github.com/lyricalpolymath/Ethereum_DaoExtraBalanceOwners

with yours and found that we have almost everything right but there is a small problem in your ETH balances.
We have the same number of addresses (11.440), the same number of transaction (22.608)
but a tiny difference in ETH value (86360144 WEI or  0.000000000086360144 ETH)

> BB (my) tot ETH    - bbtotals: 344917.57992346864402677
>     BP (your) tot ETH - bptotals: 344917.579923468557666626
>    difference BB-BP  in WEI: 86360144
>    difference BB-BP  in ETH: 0.000000000086360144 ETH

I've created a comparison [file here](https://raw.githubusercontent.com/lyricalpolymath/Ethereum_DaoExtraBalanceOwners/master/02_outputs/output_byOtherPeople/BPC_03_diffedAddressesAndValues.txt) / and the [script that generated it](https://github.com/lyricalpolymath/Ethereum_DaoExtraBalanceOwners/blob/master/03_outputAnalysisAndConverters/outputAnalysis_01_diffingBPandBBoutputs.js)

**the problem lies in line 86  of [your code](https://github.com/bokkypoobah/TheDAOData/blob/master/getTheDAOCreatedTokenEventsWithNonZeroExtraBalance_v3)**
where you do:
`var theDAOAmount = amount - extraBalanceAmount`

the difference **should rather be done with BigNumber**

`var theDAOAmount = amount.minus(extraBalanceAmount)`

because otherwise it truncates the last digits of the number

tiny detail :)

**Comment by bokkypoobah** [comment]
Thanks @lyricalpolymath . I later worked out how to fix my rounding issues using BigNumber and `.plus(...)` and will use `.minus(...)` in any of my new calculations. I won't change the figures in the results here just yet as the numbers are close enough (9 decimal places is OK for me). I'll update my front page to state that the results are to 9 decimal places until (if) I revise the figures.

**Comment by bokkypoobah** [comment]
And thanks for confirming the data in http://ethereum.stackexchange.com/a/8342/1268 .

**Comment by lyricalpolymath** [comment]
thank you in the first place :) for showing us how to do it. 👍

**Comment by bokkypoobah** [comment]
Hi @lyricalpolymath , I've just uploaded v4 with the rounding errors fixed by using BigNumber maths. See the top of the front page. However my number are slightly different to yours:

```
BB (my) tot ETH - bbtotals: 344917.57992346864402677
BP (your) tot ETH - bptotals: 344917.579923468557666626
difference BB-BP in WEI: 86360144
difference BB-BP in ETH: 0.000000000086360144 ETH
v4 344917.579923468644033437
```

The difference is after the 13th decimal place
