### ISSUE TITLE
reconcileExtraBalTokenValues returns no data

### ISSUE THREAD

**Issue by Arachnid** [bokkypoobah/TheDAOData#3]
Running on a freshly (full-)synced Geth node:

```
Header  From    TokenOwner  CreatedBy   BlockNumber TxHash  Timestamp   GMTDateTime Amount  TheDAOAmount    extraBalanceAmount  TheDAOTokens    GasUsed GasPrice    Cost    Nonce   Error
Header  TokenOwner  extraBalanceAmount  extraBalTokenAmount extraBalTokenDiff
Summary records 0
Summary amountTotal 0
Summary theDAOAmountTotal   0
Summary extraBalanceAmountTotal 0
Summary extraBalTokenContractAmountTotal    0
Summary extraBalTokenContractDiffTotal  0
Summary extraBalTokenContractTotalSupply    344917.580854976758120496
Summary theDAOTokensTotal   0

```

It appears to not be returning any events at all.

**Comment by bokkypoobah** [comment]
Hi Nick, you'll have to run the script against a non `--fast` synced chain as I use the `debug.traceTransaction(...)` API to get the correct values.

**Comment by Arachnid** [comment]
I am running it against a full-synced node, built from the latest 'develop' head. geth complains if you try and fetch nodes that don't exist (eg, past events or transactions) too, which it's not doing here.

**Comment by bokkypoobah** [comment]
I'm caught up for the next 3-4 hours, sorry. I'll get back after that.

**Comment by bokkypoobah** [comment]
Hi Arachnid, is the issue still occurring?

**Comment by Arachnid** [comment]
Yes; I'm syncing again from master instead of develop, but it's not yet done, so I can't report results on that yet.

**Comment by bokkypoobah** [comment]
OK. I'll be online for the next 2 hours.

**Comment by Arachnid** [comment]
Have you (or anyone else) tried the script on a freshly (full-) synced geth node?

**Comment by bokkypoobah** [comment]
I don't know about anyone else, but @lyricalpolymath looked at my script and checked out the results. @ledgerwatch ran and modified the script to generate the results for the ExtraBalToken contract. I'll test it out in about half an hour.

**Comment by bokkypoobah** [comment]
I've re-run the script and it works as expected.
![screenshot from 2016-09-16 10 01 41](https://cloud.githubusercontent.com/assets/17121975/18571375/42f87ffa-7bf5-11e6-9254-2b207f2d9634.png)

**Comment by Arachnid** [comment]
I've determined that a full sync off develop seems to fail, while a full sync off master seems to succeed. As soon as I've run the script, I'll be filing a bug against geth.
